// Predefined list of locations for meetup events
// Format: "City, State, Country" or "City, Country"
export const MEETUP_LOCATIONS = [
  "New York City, NY, US",
  "Los Angeles, CA, US",
  "Chicago, IL, US",
  "Houston, TX, US",
  "Phoenix, AZ, US",
  "Philadelphia, PA, US",
  "San Antonio, TX, US",
  "San Diego, CA, US",
  "Dallas, TX, US",
  "San Jose, CA, US",
  "Austin, TX, US",
  "Jacksonville, FL, US",
  "Fort Worth, TX, US",
  "Columbus, OH, US",
  "Charlotte, NC, US",
  "San Francisco, CA, US",
  "Indianapolis, IN, US",
  "Seattle, WA, US",
  "Denver, CO, US",
  "Washington, DC, US",
  "Boston, MA, US",
  "El Paso, TX, US",
  "Nashville, TN, US",
  "Detroit, MI, US",
  "Oklahoma City, OK, US",
  "Portland, OR, US",
  "Las Vegas, NV, US",
  "Memphis, TN, US",
  "Louisville, KY, US",
  "Baltimore, MD, US",
  "Milwaukee, WI, US",
  "Albuquerque, NM, US",
  "Tucson, AZ, US",
  "Fresno, CA, US",
  "Sacramento, CA, US",
  "Kansas City, MO, US",
  "Mesa, AZ, US",
  "Atlanta, GA, US",
  "Omaha, NE, US",
  "Raleigh, NC, US",
  "Miami, FL, US",
  "Oakland, CA, US",
  "Minneapolis, MN, US",
  "Tulsa, OK, US",
  "Cleveland, OH, US",
  "Wichita, KS, US",
  "Arlington, TX, US",
  "New Orleans, LA, US",
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Toronto, ON, CA",
  "Vancouver, BC, CA",
  "Montreal, QC, CA",
  "Sydney, NSW, AU",
  "Melbourne, VIC, AU",
  "Brisbane, QLD, AU",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Paris, France",
  "Lyon, France",
  "Marseille, France",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Singapore, Singapore",
  "Hong Kong, Hong Kong",
  "Dubai, UAE",
  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Mexico City, Mexico",
  "Buenos Aires, Argentina",
  "Lima, Peru",
  "Bogotá, Colombia",
  "Santiago, Chile",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Cairo, Egypt",
  "Lagos, Nigeria",
  "Nairobi, Kenya",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
];

