export const ALL_SKILLS = [
  "Accounting",
  "Advertising",
  "Agriculture",
  "Algorithm Design",
  "Alternator Repair",
  "Animal Care",
  "App Design",
  "Appraisals",
  "Architectural Design",
  "Art",
  "Audio Engineering",
  "Augmented Reality",
  "Automation",
  "AV Setup",
  "Blockchain",
  "Bookkeeping",
  "Brand Strategy",
  "Budgeting",
  "Business Analysis",
  "Business Development",
  "CAD",
  "Call Center",
  "Career Coaching",
  "Cash Flow Management",
  "Catering",
  "Celestial Navigation",
  "Change Management",
  "Childcare",
  "Clinical Research",
  "Cloud Computing",
  "Coaching",
  "Coding",
  "Cold Calling",
  "Collection & Recovery",
  "Communication",
  "Compliance",
  "Conflict Resolution",
  "Construction",
  "Content Creation",
  "Content Strategy",
  "Contract Negotiation",
  "Copywriting",
  "Cooking",
  "Corporate Training",
  "Counseling",
  "Court Reporting",
  "Creative Writing",
  "CRM",
  "Customer Service",
  "Cybersecurity",
  "Data Analysis",
  "Data Engineering",
  "Data Science",
  "Database Management",
  "Debugging",
  "De-escalation",
  "DevOps",
  "Digital Marketing",
  "Direct Mail",
  "Driving",
  "Education",
  "Electrical",
  "E-mail Marketing",
  "Emergency Response",
  "Energy Management",
  "Event Planning",
  "Executive Coaching",
  "Excel",
  "Facilities Management",
  "Financial",
  "Fine Arts",
  "First Aid & CPR",
  "Food Safety",
  "Fundraising",
  "Gardening",
  "General Maintenance",
  "Graphic Design",
  "Guitar",
  "Hardware Repair",
  "Health Coaching",
  "Healthcare Administration",
  "Help Desk",
  "Home Automation",
  "Home Cleaning",
  "Home Improvement",
  "Home Maintenance",
  "Home Organization",
  "Home Repair",
  "Human Resources",
  "Home Security",
  "Home Staging",
  "Home Theater",
  "HVAC",
  "Illustration",
  "Import/Export",
  "Industrial Design",
  "Information Architecture",
  "Insurance",
  "Interior Design",
  "Inventory Management",
  "IoT",
  "IT Management",
  "JavaScript",
  "Kanban",
  "Keynote Speaking",
  "KPI Tracking",
  "Landscaping",
  "Language Teaching",
  "Leadership",
  "Legal",
  "Lifeguarding",
  "Logistics",
  "Machine Learning",
  "Maintenance",
  "Manufacturing",
  "Market Research",
  "Marketing",
  "Mathematics",
  "Mechanical Design",
  "Mechanic",
  "Meditation Instruction",
  "Medical",
  "Medical Coding",
  "Mentoring",
  "Mobile Development",
  "Modeling (3D)",
  "Motion Graphics",
  "Network Administration",
  "Negotiation",
  "Nutrition",
  "Occupational Safety",
  "Office Management",
  "Operations",
  "Payroll",
  "Photography",
  "Plumber",
  "Policy Analysis",
  "Power BI",
  "Presentation Design",
  "Press Relations",
  "Procurement",
  "Product Management",
  "Product Photography",
  "Project Management",
  "Programming",
  "Proofreading",
  "Public Speaking",
  "Public Relations",
  "Psychotherapy",
  "QA Testing",
  "Real Estate",
  "Recruiting",
  "Ride Sharing",
  "Risk Management",
  "Robotics",
  "Sales",
  "Search Engine Optimization",
  "Security",
  "Social Media",
  "Solar Installation",
  "Sourcing",
  "Spanish",
  "Spreadsheet Modeling",
  "Stakeholder Management",
  "Statistical Analysis",
  "Stock Trading",
  "Supply Chain",
  "Sustainability",
  "Systems Administration",
  "Tax Preparation",
  "Teaching",
  "Technical Writing",
  "Technology",
  "Tech Support",
  "Telemedicine",
  "Testing Automation",
  "Time Management",
  "Trade Skills",
  "Translation",
  "Transportation",
  "Troubleshooting",
  "UX Design",
  "UI Design",
  "Videography",
  "Virtual Assistance",
  "Voiceover",
  "Wearables",
  "Web Development",
  "Welding",
  "Wellness Coaching",
  "Writing",
  "Yoga Instruction",
  ];